### ISSUE TITLE
Building Docker image from Dockerfile fails

### ISSUE THREAD

**Issue by pablochacin** [kubic-project/registries-operator#9]
Running a `docker build -t <label> .` form the project's root directory generates the following error:

> make: *** No rule to make target 'deps'.  Stop.
make: Leaving directory '/go/src/github.com/kubic-project/registries-operator'
The command '/bin/sh -c make -C $BUILD_DIR clean deps' returned a non-zero code: 2

The offending command in the `Dockerfile` is `RUN make -C $BUILD_DIR clean deps`

**Comment by MalloZup** [comment]
@pablochacin  i think you fixed this one right?

**Comment by MalloZup** [comment]
@pablochacin  i am closing thx for this :cupid:
